# Default values for eksdemo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Release-wide Values
replicas: 2
version: 'latest'


image:
  tag: latest
  repository: 474054470595.dkr.ecr.us-east-1.amazonaws.com/exter-ecrdo-wcu0xdu0y35e
  pullPolicy: Always
